# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: predict_engine.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'predict_engine.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14predict_engine.proto\x12\x10predictengine.v1\x1a\x1cgoogle/protobuf/struct.proto\"\x0f\n\rHealthRequest\"\xc1\x01\n\x0eHealthResponse\x12\x0e\n\x06status\x18\x01 \x01(\t\x12\x14\n\x0cservice_name\x18\x02 \x01(\t\x12\x12\n\nmodel_path\x18\x03 \x01(\t\x12\x14\n\x0cmodel_exists\x18\x04 \x01(\x08\x12\x14\n\x0cmodel_loaded\x18\x05 \x01(\x08\x12\x18\n\x10model_input_name\x18\x06 \x01(\t\x12\x1a\n\x12model_output_names\x18\x07 \x03(\t\x12\x13\n\x0bmodel_error\x18\x08 \x01(\t\"g\n\x0ePredictRequest\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12\x15\n\rfeature_names\x18\x02 \x03(\t\x12*\n\x04rows\x18\x03 \x03(\x0b\x32\x1c.predictengine.v1.FeatureRow\"<\n\nFeatureRow\x12.\n\x06values\x18\x01 \x03(\x0b\x32\x1e.predictengine.v1.FeatureValue\"\xa3\x01\n\x0c\x46\x65\x61tureValue\x12\x16\n\x0c\x64ouble_value\x18\x01 \x01(\x01H\x00\x12\x13\n\tint_value\x18\x02 \x01(\x03H\x00\x12\x16\n\x0cstring_value\x18\x03 \x01(\tH\x00\x12\x14\n\nbool_value\x18\x04 \x01(\x08H\x00\x12\x30\n\nnull_value\x18\x05 \x01(\x0e\x32\x1a.google.protobuf.NullValueH\x00\x42\x06\n\x04kind\"U\n\x0fPredictResponse\x12\x12\n\nrequest_id\x18\x01 \x01(\t\x12.\n\x07outputs\x18\x02 \x03(\x0b\x32\x1d.predictengine.v1.ModelOutput\"E\n\x0bModelOutput\x12\x0c\n\x04name\x18\x01 \x01(\t\x12(\n\x06tensor\x18\x02 \x01(\x0b\x32\x18.predictengine.v1.Tensor\"\x7f\n\x06Tensor\x12\r\n\x05\x64type\x18\x01 \x01(\t\x12\r\n\x05shape\x18\x02 \x03(\x03\x12\x15\n\rdouble_values\x18\x03 \x03(\x01\x12\x14\n\x0cint64_values\x18\x04 \x03(\x03\x12\x15\n\rstring_values\x18\x05 \x03(\t\x12\x13\n\x0b\x62ool_values\x18\x06 \x03(\x08\x32\xac\x01\n\rPredictEngine\x12K\n\x06Health\x12\x1f.predictengine.v1.HealthRequest\x1a .predictengine.v1.HealthResponse\x12N\n\x07Predict\x12 .predictengine.v1.PredictRequest\x1a!.predictengine.v1.PredictResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_engine_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_HEALTHREQUEST']._serialized_start=72
  _globals['_HEALTHREQUEST']._serialized_end=87
  _globals['_HEALTHRESPONSE']._serialized_start=90
  _globals['_HEALTHRESPONSE']._serialized_end=283
  _globals['_PREDICTREQUEST']._serialized_start=285
  _globals['_PREDICTREQUEST']._serialized_end=388
  _globals['_FEATUREROW']._serialized_start=390
  _globals['_FEATUREROW']._serialized_end=450
  _globals['_FEATUREVALUE']._serialized_start=453
  _globals['_FEATUREVALUE']._serialized_end=616
  _globals['_PREDICTRESPONSE']._serialized_start=618
  _globals['_PREDICTRESPONSE']._serialized_end=703
  _globals['_MODELOUTPUT']._serialized_start=705
  _globals['_MODELOUTPUT']._serialized_end=774
  _globals['_TENSOR']._serialized_start=776
  _globals['_TENSOR']._serialized_end=903
  _globals['_PREDICTENGINE']._serialized_start=906
  _globals['_PREDICTENGINE']._serialized_end=1078
# @@protoc_insertion_point(module_scope)
